'use client';

import React, { useState } from 'react';

export default function SubIdsPage() {
  const [selectedTab, setSelectedTab] = useState<'manual' | 'auto'>('auto');
  const [batchCount, setBatchCount] = useState<number>(20);
  const [manualSponsorId, setManualSponsorId] = useState<string>('GR00001');

  // Owned IDs available for manual Sub-ID sponsor selection
  const ownedIds = [
    { id: 1, display: 'GR00001 (Main ID)' },
    { id: 2, display: 'GR00002 (Sub-ID 1)' },
    { id: 3, display: 'GR00003 (Sub-ID 2)' },
    { id: 4, display: 'GR00004 (Sub-ID 3)' },
  ];

  const totalBatchCost = batchCount * 100;

  const handleCreateBatch = (e: React.FormEvent) => {
    e.preventDefault();
    alert(`Initiating Auto-Create Batch for ${batchCount} Sub-IDs (${totalBatchCost} USDT). Requires wallet approval.`);
  };

  const handleCreateManual = (e: React.FormEvent) => {
    e.preventDefault();
    alert(`Initiating Single Sub-ID creation under sponsor ${manualSponsorId} (100 USDT).`);
  };

  return (
    <div className="space-y-8 max-w-4xl mx-auto">
      <div>
        <span className="text-xs font-semibold text-cyan-400 uppercase tracking-wider">Sub-ID Management Hub</span>
        <h1 className="text-3xl font-black text-slate-100 mt-1">Create Sub-IDs</h1>
        <p className="text-sm text-slate-400 mt-1">
          Sub-IDs inherit sponsor relationships exclusively from your owned ID network. Level income generated by Sub-IDs is aggregated to your Main User account.
        </p>
      </div>

      {/* Tab Switcher */}
      <div className="flex bg-slate-900/90 p-1.5 rounded-2xl border border-slate-800 max-w-md">
        <button
          onClick={() => setSelectedTab('auto')}
          className={`flex-1 py-2.5 rounded-xl font-bold text-sm transition-colors ${
            selectedTab === 'auto'
              ? 'bg-gradient-to-r from-cyan-500 to-emerald-500 text-slate-950 shadow-md'
              : 'text-slate-400 hover:text-slate-200'
          }`}
        >
          Auto Create (1–20 Batch)
        </button>
        <button
          onClick={() => setSelectedTab('manual')}
          className={`flex-1 py-2.5 rounded-xl font-bold text-sm transition-colors ${
            selectedTab === 'manual'
              ? 'bg-gradient-to-r from-cyan-500 to-emerald-500 text-slate-950 shadow-md'
              : 'text-slate-400 hover:text-slate-200'
          }`}
        >
          Manual Create (Single)
        </button>
      </div>

      {/* Tab Content: Automatic Batch Creation */}
      {selectedTab === 'auto' && (
        <div className="glass-panel p-6 lg:p-8 rounded-3xl border border-slate-800 space-y-6">
          <div>
            <h2 className="text-xl font-bold text-slate-100">Automatic 2-by-2 Binary Batch System</h2>
            <p className="text-xs text-slate-400 mt-1 leading-relaxed">
              Generates a deterministic breadth-first binary sponsor tree. Sub 1 & 2 sponsored by Main ID; Sub 3 & 4 sponsored by Sub 1; Sub 5 & 6 sponsored by Sub 2, and so forth.
            </p>
          </div>

          <form onSubmit={handleCreateBatch} className="space-y-6">
            <div>
              <div className="flex justify-between items-center mb-2">
                <label className="text-sm font-semibold text-slate-200">Select Batch Quantity (Max 20)</label>
                <span className="text-sm font-bold text-cyan-400">{batchCount} Sub-IDs</span>
              </div>
              <input
                type="range"
                min={1}
                max={20}
                value={batchCount}
                onChange={(e) => setBatchCount(parseInt(e.target.value))}
                className="w-full h-2 bg-slate-800 rounded-lg appearance-none cursor-pointer accent-cyan-500"
              />
              <div className="flex justify-between text-xs font-mono text-slate-500 mt-1">
                <span>1</span>
                <span>5</span>
                <span>10</span>
                <span>15</span>
                <span>20</span>
              </div>
            </div>

            {/* Cost Preview Card */}
            <div className="glass-card p-5 rounded-2xl border border-slate-700/60 bg-slate-900/60 space-y-2">
              <div className="flex justify-between text-xs text-slate-400">
                <span>Entry Fee Per Sub-ID</span>
                <span className="font-semibold text-slate-200">100 USDT</span>
              </div>
              <div className="flex justify-between text-xs text-slate-400">
                <span>Selected Quantity</span>
                <span className="font-semibold text-slate-200">{batchCount} Sub-IDs</span>
              </div>
              <div className="border-t border-slate-800 pt-2 flex justify-between text-sm font-bold">
                <span className="text-slate-200">Total Required USDT</span>
                <span className="text-emerald-400 text-lg">${totalBatchCost} USDT</span>
              </div>
            </div>

            {/* Structure Preview Matrix */}
            <div className="space-y-2">
              <span className="text-xs font-bold text-slate-400 uppercase">Deterministic Sponsor Tree Preview</span>
              <div className="bg-slate-900/90 p-4 rounded-2xl border border-slate-800/80 font-mono text-xs text-slate-300 space-y-1 max-h-40 overflow-y-auto">
                <p className="text-cyan-400 font-semibold">Main ID (GR00001)</p>
                <p className="pl-4">├── Sub-1 (GR00002) & Sub-2 (GR00003)</p>
                {batchCount >= 4 && <p className="pl-8">├── Sub-1 ── Sub-3 (GR00004) & Sub-4 (GR00005)</p>}
                {batchCount >= 6 && <p className="pl-8">├── Sub-2 ── Sub-5 (GR00006) & Sub-6 (GR00007)</p>}
                {batchCount > 6 && <p className="pl-12 text-slate-500">... and so on up to Sub-{batchCount}</p>}
              </div>
            </div>

            <button
              type="submit"
              className="w-full gradient-btn py-3.5 rounded-xl font-bold text-slate-950 text-sm shadow-lg shadow-cyan-500/20"
            >
              Approve & Create {batchCount} Sub-IDs (${totalBatchCost} USDT)
            </button>
          </form>
        </div>
      )}

      {/* Tab Content: Manual Single Creation */}
      {selectedTab === 'manual' && (
        <div className="glass-panel p-6 lg:p-8 rounded-3xl border border-slate-800 space-y-6">
          <div>
            <h2 className="text-xl font-bold text-slate-100">Manual Single Sub-ID Creation</h2>
            <p className="text-xs text-slate-400 mt-1">
              Select a specific sponsor from your owned IDs list. Unrelated external IDs are strictly prohibited by protocol smart contracts.
            </p>
          </div>

          <form onSubmit={handleCreateManual} className="space-y-4">
            <div>
              <label className="block text-xs font-semibold text-slate-300 mb-1">Select Permitted Sponsor ID</label>
              <select
                value={manualSponsorId}
                onChange={(e) => setManualSponsorId(e.target.value)}
                className="w-full bg-slate-900 border border-slate-700 rounded-xl px-4 py-2.5 text-sm text-slate-100 focus:outline-none focus:border-cyan-500"
              >
                {ownedIds.map((item) => (
                  <option key={item.id} value={item.display}>
                    {item.display}
                  </option>
                ))}
              </select>
              <p className="text-[11px] text-slate-500 mt-1">
                🔒 On-chain check enforces `users[sponsorId].ownerMainUserId == msg.sender`
              </p>
            </div>

            <button
              type="submit"
              className="w-full gradient-btn py-3.5 rounded-xl font-bold text-slate-950 text-sm shadow-md"
            >
              Create Sub-ID (100 USDT)
            </button>
          </form>
        </div>
      )}
    </div>
  );
}
